#!/bin/bash


timedatectl set-timezone Europe/Amsterdam && echo LANG=en_GB.UTF-8 > /etc/locale.conf && export LANG=en_GB.UTF-8 && echo barch > /etc/hostname &&
passwd root && pacman -S grub && grub-install --target=i386-pc /dev/sda1 && grub-mkconfig -o /boot/grub/grub.cfg 
