#!/bin/bash

echo boot root home &&
pacman -Syy && pacman -S reflector && reflector --country Netherlands --country Germany --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist &&
echo pacman is correct nu partities && cfdisk


mkfs.fat -F32 /dev/sda1 && mkfs.ext4 /dev/vda2 && mkfs.ext4 /dev/vda3 && echo PARTION KLAAR. &&

mount /dev/vda3 /mnt && mkdir /mnt/home && mkdir /mnt/boot && mount /dev/vda2 /mnt/home && mount /dev/vda1 /mnt/boot &&
pacstrap /mnt base linux linux-firmware vim nano &&
genfstab -U /mnt >> /mnt/etc/fstab && cp barch2-install -t /mnt && arch-chroot /mnt
