#!/bin/bash

echo boot root home swap &&
pacman -Syy && pacman -S reflector && reflector --country Netherlands --country Germany --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist &&
echo pacman is correct nu partities && cfdisk


mkfs.ext4 /dev/sda2 && mkfs.fat /dev/sda1 && mkfs.ext4 /dev/sda3 && && mkswap /dev/sda4 && echo PARTION KLAAR. &&

mount /dev/sda3 /mnt && mkdir /mnt/home && mkdir /mnt/boot && mount /dev/sda2 /mnt/home && mount /dev/sda1 /mnt/boot &&
pacstrap /mnt base linux linux-firmware vim nano &&
genfstab -U /mnt >> /mnt/etc/fstab && cp barch2-install -t /mnt && arch-chroot /mnt && chmod 777 barch2-install
